### ISSUE TITLE
xrmApp.Entity.SetValue(new LookupItem is saying Value does not exist

### ISSUE THREAD

**Issue by farrows3** [Microsoft/EasyRepro#149]
Hi
I am customizing the App createcase.cs sample to work against a custom form.  However when I try to insert a known value into a lookup field it is returning an error and saying the value is not there.

the programme_name of "Testing" is there. It seems to find it, but then not select it

Can anyone point me in right direction/help ?

Code line
xrmApp.Entity.SetValue(new LookupItem { Name = "programmes_name", Value = "Testing" });

Error Message
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateCaseUCI.UCITestCreateCase threw exception: 
System.InvalidOperationException: List does not have Testing.

**Comment by TYLEROL** [comment]
Thanks for raising this issue @farrows3 . While working on another set of issues recently with the SetValue() method on Lookups with the Unified Interface I also observed this issue.


There are two main issues I've noticed:

1.  Case sensitivity of the item name vs. the supplied lookup value (e.g. testing vs. Testing)

2.  After sending in the key value, the lookup window will temporarily close and re-activate. In this process, the key value that is sent is lost and the searched item is no longer visible. This also results in the 'List does not have X' error message.

I am working on fixes for both scenarios and hope we can get them out as soon as possible. The second scenario has been the more difficult one to stabilize consistently.

Once we have a set of fixes available and checked-in I'll link the PR here. If you're observing behavior outside of the two scenarios described above please let me know and I can review further.


Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@farrows3 - Thanks for your patience as it took us a bit longer to get back to this one. A PR, #192, has been merged into the beta/v9.0.2 branch and should hopefully resolve this issue for you. The following changes were made as a part of the fix:

1. Checking for results in the flyout dialog is no longer case sensitive
2. Lookup flyout dialog should remain open, avoiding unexpected 'value does not exist' errors
3. Added index parameter to allow picking of any value available in the drop down, default to first item in the list if no index parameter is provided
4. Allow input search text of "" for testing the 'Recently Viewed' drop down, if recently viewed records are available for the user
5. If the lookup field already contains a value, clear the field (hover, then click the delete button), then apply the new value as desired.

If you have questions about the fixes, or if you continue to face issues with this scenario, please re-open this issue.

Best Regards,
Tyler

**Comment by rupakraj6** [comment]
Hi TYLEROL,
  
 is this fix available in the latest releases/9.1 branch. I seem to face this issue as shown below.

Microsoft.Dynamics365.UIAutomation.Sample.UCI.Create.CreateForecast.UCITestCreateForecast threw exception: 
System.InvalidOperationException: List does not contain a record with the name:  XXXX

**Comment by silverbrewer07** [comment]
Hi @TYLEROL, 

I am also still having this issue. It works fine for me if the lookup is on the first tab of the UCI but not if its in a different tab. It work about 50% of the time. 

Thanks
Beau

**Comment by srinu24k** [comment]
It seems this issue is still replicates now. Have been working on this project but suddenly today I am facing this issue. Any help, how to resolve it.
![image](https://user-images.githubusercontent.com/38425186/89768643-7ca3db00-db19-11ea-8dbc-0fd643d718b1.png)

**Comment by nareshbak** [comment]
We are also seeing this issue. Any resolution to this. Please help.

**Comment by maheshmallamsc** [comment]
Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateContactUCI.UCITestCreateContact threw exception: 
    System.InvalidOperationException: List does not contain a record with the name:  Romania 
  Stack Trace: 
    WebClient.SetLookUpByValue(IWebDriver driver, LookupItem control, Int32 index) line 1926
    <>c__DisplayClass64_0.<SetValue>b__0(IWebDriver driver) line 1833
    DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) line 28
    BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) line 136
    BrowserCommand`1.Execute(IWebDriver driver) line 36
    BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) line 182
    WebClient.SetValue(LookupItem control, Int32 index) line 1809
    Entity.SetValue(LookupItem control, Int32 index) line 389
    CreateContactUCI.UCITestCreateContact() line 73

**Comment by maheshmallamsc** [comment]
this is the issue geeting while selecting value in lookup in contact form
